class DBError(Exception):
    pass

class DataError(Exception):
    pass
